### ISSUE TITLE
Triggers Chrome and half the world's AVs?

### ISSUE THREAD

**Issue by MulleDK19** [petoolse/petools#10] opened 2020-04-10 09:02 UTC
What is this new version doing that would cause half the world's AVs to flag it, and make Chrome refuse to download it with no option to continue at own risk?

https://www.virustotal.com/gui/file/2198c71f1bbf4809a1f4af58e0b11aac9c33edfee0be7ef29f6fe798dc7b6e8d/detection

v1.5 only triggers 3 AVs, and isn't flagged by Chrome.

**Comment by upiter** [comment] 2020-04-17 18:36
Duplicate of #7

**Closed as completed by upiter** 2020-04-17 18:36 UTC
